### ISSUE TITLE
checkDevServer not working with vite v2.4.0

### ISSUE THREAD

**Issue by watarutmnh** [nystudio107/craft-vite#11]
### Describe the bug
With 'checkDevServer' => true, assets in src directory are not used even though vite dev server is running.
It works ok with vite v2.3.8 but not with v2.4.0 and newer version.

### To reproduce
Steps to reproduce the behaviour:
1. Set 'checkDevServer' => true
2. Access the site while dev server running

### Expected behaviour
It should reference the assets in the src directory, but instead the build assets in the dist directory.
The assets in the src directory are still accessible.

### Versions
- Plugin version: 1.0.11
- Craft version: 3.6.17

**Comment by khalwat** [comment]
Fixed in 1.0.12 -> https://github.com/nystudio107/craft-vite/releases/tag/1.0.12

Diff: https://github.com/nystudio107/craft-plugin-vite/commit/13f74fe2a6f77b7079ad1ec471411a77c90c6987
