### ISSUE TITLE
Assets loaded from primary site causing CORS error

### ISSUE THREAD

**Issue by kan-erik** [nystudio107/craft-vite#15]
### Describe the bug
When running in production, assets are loaded with absolute URLs from the Primary site URL, not the current site.

For example:
Multisite using different domains:
sitea.com (primary)
siteb.com
sitec.com

assets on siteb.com and sitec.com will then load from sitea.com/assets/xxx causing CORS errors.

### To reproduce
Create a multisite setup using different domains per site.

### Expected behaviour
Assets should be loaded from the visited site domain, not from the craft assigned primary domain.

### Versions
- Vite plugin version: 1.0.16
- Vite js version: 2.6.4
- Craft version: 3.7.16

**Comment by khalwat** [comment]
This _probably_ doesn't have anything to do with the Vite plugin -- what is in your generated `manifest.json` after you do a build? I'm assuming absolute URLs will be listed in there?

If so, that's what it'll try to load... and the generated URLs are based on your `vite.config.js` setup.

**Comment by kan-erik** [comment]
That was my initial thought too, but the manifest-urls are relative:

```json
{
  "src/js/site-legacy.js": {
    "file": "assets/app-legacy.a6ed90f5.js",
    "src": "src/js/site-legacy.js",
    "isEntry": true
  },
  "vite/legacy-polyfills": {
    "file": "assets/polyfills-legacy.c7682d79.js",
    "src": "vite/legacy-polyfills",
    "isEntry": true
  },
  "src/js/site.js": {
    "file": "assets/app.0df5c9dc.js",
    "src": "src/js/site.js",
    "isEntry": true,
    "css": [
      "assets/app.ab7238fa.css"
    ]
  }
}
```

**Comment by khalwat** [comment]
Ah okay right, what it does is it combines those URLs with your settings from your `config/vite.php`:

https://github.com/nystudio107/craft-plugin-vite/blob/develop/src/services/ViteService.php#L490

```php
    /**
     * @var string The public URL to the dev server (what appears in `<script src="">` tags
     */
    'devServerPublic' => 'http://localhost:3000/',

    /**
     * @var string The public URL to use when not using the dev server
     */
    'serverPublic' => App::env('PRIMARY_SITE_URL') . '/dist/',
```

So if you wanted it to be multi-site aware, you could make the `config/vite.php` a [Multi-Environment config file](https://craftcms.com/docs/2.x/multi-environment-configs.html) and explicitly list each domain on a per-site basis, or you could probably leave `serverPublic` a relative URL.

**Comment by kan-erik** [comment]
I had forgotten about that setting. I have a multi-environment `config/general.php` already, so just swapped in my `@web` alias instead (`'@web/dist/'`).

Thank you Andrew.
