### ISSUE TITLE
Suggested Vite-Processed Assets path is potentially outdated

### ISSUE THREAD

**Issue by joepagan** [nystudio107/craft-vite#17]
### Describe the bug

Hey, hope all is good, 

https://nystudio107.com/docs/vite/#vite-processed-assets suggests we need:

`vite.config.js`:
```js
server: {
   origin: 'http://localhost:3000/src/', 
   host: '0.0.0.0',
}
```

Though with vite 2.6.14 where we have the following bg image set:
```css
background-image:url(/src/images/marker.svg);
```
It gives us:
```css
background-image: url(https://localhost:3000/src//@fs/var/www/html/src/images/marker.svg)
```

Looking at your docs I presume vite has changed the resulting path the dev server gives you instead with a new file-system based absolute path now.

Instead it looks like we need in vite.config.js:
```js
origin: "https://localhost:3000",
```

which gives me:
```
background-image: url(https://localhost:3000/@fs/var/www/html/src/images/marker.svg);
```

(and a visible asset on the frontend)

### Versions
- Plugin version:  "nystudio107/craft-vite": "1.0.16",
- Vite version: 2.6.14
- Craft version:  "craftcms/cms": "3.7.13",

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-vite/commit/62e3cd0e001b60c585d94e560129c9cc6be09e36

(you may or may not want the trailing `/` on the `origin:` URL depending on your setup)

**Comment by darylknight** [comment]
Might be worth updating the article too https://nystudio107.com/blog/using-vite-js-next-generation-frontend-tooling-with-craft-cms#vite-processed-assets

![image](https://user-images.githubusercontent.com/1250017/144503386-925c8be5-6651-463d-9d00-1f38998fb8a4.png)

**Comment by khalwat** [comment]
Just did thx @darylknight
