### ISSUE TITLE
Using static assets and build mode

### ISSUE THREAD

**Issue by svondervoort** [nystudio107/craft-vite#27]
### Question
Following the [docs](https://nystudio107.com/docs/vite/#the-asset-function) I don't really understand how the whole static assets work if they are not imported using CSS or Javascript. I use the `rollup-plugin-copy` as mentioned but do I also use the `{{ craft.vite.asset("...") }}`?

In `build` mode with the **.env** `ENVIRONMENT = production` it shows a `(unknown)` as the src of the image.

### Additional context
I notice if I import the image in my `app.js` and `console.log` the image it puts the image in the manifest.json and it works. Maybe I'm missing some step of configuration here?

**Comment by davidhellmann** [comment]
Not sure if it helps but I do it this way: My fonts and static images (mostly svg) are in my public folder. I do a yarn build if i put new stuff into this folder. But most of the time it's on project start or if I check out the project. My manifest holds just css and js files.

**Comment by svondervoort** [comment]
Well the reason I would like to use Vite  is because then we can also use a plugin like vite-plugin-compress or vite-plugin-imagemin to optimize images. Now we could ofcourse optimize these assets beforehand because we have full control over the assets.

But still if you put the images in `./public` how do you reference them in the html.twig? What path do you use as src? Because I tried several ways but it only works for either `dev` or `production` mode, not both.

**Comment by davidhellmann** [comment]
I use a baseUrl var:

https://github.com/davidhellmann/craftcms-baukasten/blob/dev/craft-vite/templates/_layouts/_partials/fonts/fonts-default-preloading.twig


it's defined here:
https://github.com/davidhellmann/craftcms-baukasten/blob/dev/craft-vite/templates/_boilerplate/_layouts/layout-global-variables.twig

For SVG I use the alias method but at the end its the same. 

Edit:

https://github.com/davidhellmann/craftcms-baukasten/blob/dev/craft-vite/templates/_components/icon/icon.twig

I mean the SVG Method. 😅

**Comment by svondervoort** [comment]
@davidhellmann thanks for your input.
So your scripts in package.json would look something like this?

``` json
"scripts": {
    "dev": "vite build && vite",
    "build": "vite build"
}
```

**Comment by davidhellmann** [comment]
Do it manually but yes, this should work.

**Comment by svondervoort** [comment]
One more question:
Then why not put the images/fonts etc. in the `./web` directory instead of having them copied from the `./public`? Or is there stuff happening to the files in the background while you do a build before they are put in the `./web` folder?

**Comment by davidhellmann** [comment]
Valid question. I think it's cause the web/dist folder is not in git and it's created while the build process. My solution works fine for me. But there are other ways to solve the "problem" :) 

Maybe Andrew has other thoughts 🤔

**Comment by khalwat** [comment]
So this really is a question. you probably should be asking on a the Vite repo or in a Vite forum... this doesn't really have anything to do with the Vite plugin for Craft.

Anyway, my two cents is it sounds like you're trying to use Vite as a general build tool; if you won't be including these images via JS, I'd suggest you try other methods of things like optimizing images:

- Write a small script that uses the JavaScript packages directly to operate on the images
- Use a plugin like ImageOptimize which integrates with Craft
