### ISSUE TITLE
Need help getting it up and running

### ISSUE THREAD

**Issue by FrDH** [nystudio107/craft-vite#34]
### Question
I think I followed all the steps and feel I'm really close to getting it to work. But I keep getting this error in the console: 
Loading of module from 'http://localhost:8888/craft/src/ts/main.ts' is blocked due to a disallowed MIME type ('text/plain').

Any help would be much appreciated.

### Additional context
- Craft version 4
- plugin version 4
- Vite.js is installed
- using MAMP 6 + php 8.0.8
- site is located at http://localhost:8888/craft

file structure
<img width="200" alt="Schermafbeelding 2022-06-11 om 01 07 42" src="https://user-images.githubusercontent.com/1387163/173161097-fef9dde9-6075-4ad3-9faa-10195b3b8c04.png">

vite config 
```js
export default defineConfig(({ command }) => {
  const base = (command === 'serve') ? '/craft/public_html/' : '/dist/';
  return {
    base,
    build: {
      manifest: true,
      outDir: './public_html/dist/',
      rollupOptions: {
        input: {
          app: './src/ts/main.ts',
        },
      },
    },
  };
});
```

plugin config
```php
return [
    'useDevServer' => true, // App::env('ENVIRONMENT') === 'dev',
    'manifestPath' => '@webroot/dist/manifest.json',
    'devServerPublic' => 'http://localhost:8888/craft/',
    'serverPublic' => App::env('PRIMARY_SITE_URL') . '/dist/',
    'errorEntry' => '',
    'cacheKeySuffix' => '',
    'devServerInternal' => '',
    'checkDevServer' => false,
    'includeReactRefreshShim' => false,
    'includeModulePreloadShim' => true,
    'criticalPath' => '@webroot/dist/criticalcss',
    'criticalSuffix' =>'_critical.min.css',
];
```

index.twig
```html
{# this evaluates to true #}
{% if craft.vite.devServerRunning() %}
  dev server is running 
 {% endif %}
{{ craft.vite.script("./src/ts/main.ts") }}
```

**Comment by khalwat** [comment]
This is going to be some kind of server/local dev setup issue or an issue with the paths you're passing in via your Vite, both of which are unrelated to the Craft Vite plugin.

Here's a lead for you: https://stackoverflow.com/questions/58173204/module-was-blocked-because-of-a-disallowed-mime-type-text-html

**Comment by dr-codswallop** [comment]
I also experienced difficulty setting up Vite with Mamp, but if it help any other Mamp users in future here is a working setup. 

This is on the following basic assumptions
1. Your domain name in Mamp is `example.test` (change to suit)
2. The public root directory for the host is named `public_html`
3. You have your development js & css inside a `src` directory which is in the root of your project (`src/app.js` & `src/app.css`)
4. You will be compliing your production js/css into `public_html/dist`


vite.config.js

```
const { defineConfig } = require('vite');

module.exports = defineConfig({
    server: {
        host: 'example.test',
        port: 3000,
        strictPort: true,
        cors: true,
        open: true
    },
    build: {
        outDir: 'public_html/dist',
        emptyOutDir: true,
        manifest: true,
        rollupOptions: {
            input: {
                app: '/src/app.js',
            }
        },
    }
})

```
config/vite.php

```
use craft\helpers\App;

return [
    'useDevServer' => App::env('ENVIRONMENT') === 'dev' || App::env('CRAFT_ENVIRONMENT') === 'dev',
    'devServerPublic' => 'http://localhost:3000/',
    'devServerInternal' => 'http://localhost:3000/',
    'errorEntry' => '',
    'cacheKeySuffix' => '',
    'manifestPath' => '@webroot/dist/manifest.json',
    'serverPublic' => 'http://example.test/dist/',
    'serverInternal' => 'http://example.test/dist/',
]
```



In `src/app.js` add the following line to include your css from `src/app.css`
`import './app.css';`



Add the following into the `<head>` section your main Twig template.
`{{ craft.vite.script("./src/app.js") }}`



Run `npx vite` to start the Vite dev server. 


This final part is where I was confused for a while. Open `example.com` in a browser. **Do not open `example.com:3000`** as this will just remain a blank screen. As long as you're viewing the naked domain without a port number, then your changes to CSS etc should be immediately reflected in the browser.

The above might need some adjustment to suit your domain and directory structure but it seems to be working fine so far on various Mamp+Craft+Vite projects. No doubt there may also be further improvements which can be made but this at least gets a Mamp user up and running.

**Comment by maartenheideman** [comment]
I work with ddev and had the same issue, to fix it had to add "allowedHosts" and "cors"
```
server: {
    host: "0.0.0.0",
    port: 3000,
    allowedHosts: ["domain.ddev.site"],
    cors: true,
},
```
