### ISSUE TITLE
Question about using the origin setting

### ISSUE THREAD

**Issue by JeanLucEsser** [nystudio107/craft-vite#35]
### Question

This is about the origin setting vite added with version 2.6.

In the docs, when talking about the origin setting, you are using devServerInternal (http://localhost:3000) as an example. This is not working for me as it throws a security error and my fonts are not being loaded (I'm serving my local site over https).

As we know, devServerPublic can run over http or https whereas devServerInternal is always http. So what I'm doing is using origin with devServerPublic instead (https://projectname.ddev.site:3000) which works fine for my use case.

Question is simple:
Is there any downside to doing this?
What's the difference between using one or the other?

**Comment by khalwat** [comment]
Should be fine
