### ISSUE TITLE
Make errorEntry work for dd (die and dump)

### ISSUE THREAD

**Issue by plumduffer** [nystudio107/craft-vite#42]
### Is your feature request related to a problem? Please describe.
Have to manually refresh after dying a variable to my template.

### Describe the solution you would like
Have the plugin automatically inject the errorEntry into the dd screen as to refresh automatically after more changes.

### Describe alternatives you have considered
I thought maybe the vite-plugin-restart or other similar ones might have this option, but it doesn't seem so.

### Additional context
Nothing else to add. Thanks for all the awesome work you do!

**Comment by khalwat** [comment]
So it should already support this via the `errorEntry` config setting: https://nystudio107.com/docs/vite/#the-config-php-file

**Comment by khalwat** [comment]
Potentially releated to: https://github.com/nystudio107/craft-vite/issues/44
