### ISSUE TITLE
includeCriticalCssTags adds unwanted underscore to critical css file path

### ISSUE THREAD

**Issue by iwe-hi** [nystudio107/craft-vite#45]
### Describe the bug
We have a home template located at ```CRAFT_TEMPLATES_PATH/_templates/``` for which we create critical css with the rollup-plugin-critical package. The generated file lies at ```@webroot/dist/criticalcss/home_critical.min.css```. 

If we want to include the file with the includeCriticalCssTags variable the file is not found because an extra underscore gets added to the file path before the template name. The path looks like this: ```/craft/web/dist/criticalcss/_home_critical.min.css```. 

The same behaviour occurs when working with templates that start with an underscore.

### To reproduce
Steps to reproduce the behaviour:
1. Create a template or template directory beginning with an underscore
2. Build the critical css with rollup-plugin-critical
3. Include critical css with ```{{ craft.vite.includeCriticalCssTags('<template>') }}```
4. See no error message and also no outputted style tag

### Config files
vite.php
```php
return [
    'useDevServer' => App::env('ENVIRONMENT') === 'dev',
    'manifestPath' => '@webroot/dist/manifest.json',
    'devServerPublic' => App::env('DEV_SERVER'),
    'serverPublic' => '@web/dist/',
    'errorEntry' => 'src/js/main.js',
    'cacheKeySuffix' => '',
    'devServerInternal' => App::env('DEV_SERVER'),
    'checkDevServer' => true,
    'includeReactRefreshShim' => false,
    'includeModulePreloadShim' => true,
    'criticalPath' => '@webroot/dist/criticalcss',
    'criticalSuffix' => '_critical.min.css',
];
```
rollup-plugin-critical config
```js
critical({
    criticalUrl: '<url>',
    criticalBase: '../backend/craft/web/dist/criticalcss/',
    criticalPages: [
        {uri: '', template: 'home'},
    ],
    criticalConfig: {},
}),
```

### Versions
- Plugin version: 1.0.28
- Craft version: 3.7.55.2

**Comment by iwe-hi** [comment]
Ok, I found the problem. Our templates directory has a subdirectory called ```_templates```. In [Helper.php at line  55](https://github.com/nystudio107/craft-vite/blob/9dec2deb36d29994c0dd384e8fe7198c0fae91fb/src/services/Helper.php#L55) this subdirectory gets replaced because of its name. 

A possible solution could be to change this line that it only replaces one occurrence of the ```CRAFT_TEMPLATES_PATH``` like this:

```php
  $pos = strpos($name, $dirPrefix);

  if ($pos !== false) {
      $name = substr_replace($name, '', $pos, strlen($dirPrefix));
  }
```

**Comment by nguyenandre** [comment]
Hello, I am also having a similar problem.

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-vite/commit/4bd5c23676a51e2da3aa3ee5654d499f543df4b7 & https://github.com/nystudio107/craft-vite/commit/0e96a264099b336cc07e7ec6caa2f81a98c334d2

Released as:

Craft 3: Version 1.0.29 -> https://github.com/nystudio107/craft-vite/releases/tag/1.0.29

Craft 4: Version 4.0.4 -> https://github.com/nystudio107/craft-vite/releases/tag/4.0.4
