### ISSUE TITLE
Support React Refresh

### ISSUE THREAD

**Issue by baileydoestech** [nystudio107/craft-vite#5]
### Is your feature request related to a problem? Please describe.
Ability to use React components with HMR, currently this will error with the following during development: `Uncaught Error: @vitejs/plugin-react-refresh can't detect preamble. Something is wrong.`

### Describe the solution you would like
Injected the following script to allow ViteJS to modify HTML via the `@vitejs/plugin-react-refresh` plugin (https://vitejs.dev/guide/backend-integration.html#backend-integration).  Would be nice if the script respected the dev server that has been configured in `vite.php` config

```
<script type="module">
  import RefreshRuntime from 'http://localhost:3000/@react-refresh'
  RefreshRuntime.injectIntoGlobalHook(window)
  window.$RefreshReg$ = () => {}
  window.$RefreshSig$ = () => (type) => type
  window.__vite_plugin_react_preamble_installed__ = true
</script>
```

### Describe alternatives you have considered
Currently we are manually including the above script block conditionally when in DEV mode to enable HMR of React components.

**Comment by khalwat** [comment]
Interesting, yeah seems to make sense.

One thing of note though, those docs pages may be out of date. You don't need to include `@vite/client` at all. I was originally doing that, but noticed if I removed it, Vite included it anyway.

I'd assumed the same was the case with ReactRefresh

**Comment by baileydoestech** [comment]
Yeah agreed, `@vite/client` doesn't seem to be needed anymore, but the `RefreshRuntime` block is still required for React HMR - assuming because of the additional bootstraping it seems to do on the `window`.

Maybe just a boolean config flag in `vite.php` of the form `useReactRefresh` that injects the block?

**Comment by khalwat** [comment]
Yeah a boolean in the config would do it... was thinking if there was a more clever way to do it automatically.

**Comment by khalwat** [comment]
This will make it into the next version -- I couldn't find any real clever way to auto-detect this so probably just a boolean flag

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-plugin-vite/commit/77f72188928075eb701d3085948da993e99a4723

**Comment by khalwat** [comment]
Released in https://github.com/nystudio107/craft-vite/releases/tag/1.0.7

**Comment by khalwat** [comment]
lmk if this is working for you @lukebailey

**Comment by baileydoestech** [comment]
So after a bit of frustration, yes this is working thanks.

Issue was nothing to do with your plugin, turns out the [react refresh plugin ](https://github.com/facebook/react/blob/516b76b/packages/react-refresh/src/ReactFreshBabelPlugin.js#L430-L440) does not support class components but only functional ones.

There do seem to be a few React HMR related issues with Vite JS though:

https://github.com/vitejs/vite/issues/3002
https://github.com/vitejs/vite-plugin-react/issues/20

Warning to anyone else that comes across this.
