### ISSUE TITLE
Template named "register" breaks HMR

### ISSUE THREAD

**Issue by jan-dh** [nystudio107/craft-vite#51]
### Describe the bug
I had an issue where I had a template at the template root called `register.twig` and it breaks the HMR. Making changes to a css file (with a tailwind setup) breaks my HMR saying it can't find the register template. Renaming the template fixed the issue. 

- Plugin version: 4.0.3
- Craft version:  4.3.1

**Comment by khalwat** [comment]
Can you post the actual error message, and where it is displayed (frontend, JavaScript console, error logs, etc.)?

Because I think this very likely is not a Craft Vite plugin issue

**Comment by jan-dh** [comment]
Hmm, can't reproduce :s was ENOENT mean "No such file or directory" for "templates/register". Presuming this had sth to do with the DDEV cache.
