### ISSUE TITLE
criticalUrl in .env

### ISSUE THREAD

**Issue by interactivespace** [nystudio107/craft-vite#52]
For the different staging areas I need to define different critical urls. Is there a way to define the critical url in an .env file?

**Comment by khalwat** [comment]
Sure, you can get any of the settings for the plugin from an environment variable. See here for examples: 

https://github.com/nystudio107/craft-vite/blob/develop/src/config.php#L82

**Comment by interactivespace** [comment]
Thank you very much for this fast response. I don't quite understand how the php configuration file can overwrite the configuration in the vite.config.js file? 

```
    critical({
      criticalUrl: 'https://apache',
      criticalBase: './web/dist/',
      criticalPages: [
        { uri: '', template: 'index' },
        { uri: '/some/other/url', template: 'otherTemplate' }
      ],
      criticalConfig: {
        inline: false,
        extract: false,
        width: 1280, 
        height: 1200,
        penthouse: {
          blockJSRequests: false
        }
      },
    }),

```

**Comment by khalwat** [comment]
If you mean in the Vite config, that doesn't really have anything to do with the Craft Vite plugin

But yes, you could also use the Node [dotenv](https://www.npmjs.com/package/dotenv) package in your Vite config to read in a `.env` file for the build as well.
