### ISSUE TITLE
`inline()` function not working with relative local path

### ISSUE THREAD

**Issue by jrrdnx** [nystudio107/craft-vite#55]
The `craft.vite.inline()` function doesn't output the contents of my CSS file when the `serverPublic` setting in the config uses only a relative local path and doesn't include the base URL.

Essentially, this line:

```
{{ craft.vite.inline(craft.vite.entry('src/scss/critical.scss')) }}
```

works ONLY when

```
'serverPublic' => App::env('BASE_URL') . '/dist/',
```

but NOT when

```
'serverPublic' => '/dist/',
```

`craft.vite.entry('src/scss/critical.scss')` outputs the correct URL in both scenarios, so it's just the `inline()` function that doesn't seem to be working in the latter.

There is an error output to the web log, but it's the same in both scenarios as well:

```
2023-01-13 16:43:03 [web.ERROR] [nystudio107\pluginvite\helpers\FileHelper::fetchResponse] cURL error 7: Failed to connect to localhost port 5173 after 1274 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://localhost:5173/__vite_ping {"memory":1923336} 
```

Not a critical issue, but we would prefer to use relative paths for these resources.

### Versions
- Plugin version: 4.0.4
- Craft version: 4.3.6.1

**Comment by khalwat** [comment]
So at least for now, I think you're going to need to use absolute paths. If you want to do a PR for this feature though, I'm open to it!

**Comment by jrrdnx** [comment]
I looked into this, but I wasn't quite sure how to build this in while ensuring backwards compatibility. I did track it down to [this file in craft-plugin-vite](https://github.com/nystudio107/craft-plugin-vite/blob/0edc227a122d33288541d88ab72aa406973447c7/src/variables/ViteVariableTrait.php#L112). The URL is web-relative and not server-relative so I was able to fix it in my case by prefixing it with `@webroot`:

```
{{ craft.vite.inline('@webroot' ~ craft.vite.entry('src/scss/critical.scss')) }}
```
