### ISSUE TITLE
craft.vite.asset no longer matches manifest format in Vite 3.x || 4.x

### ISSUE THREAD

**Issue by Kashkin** [nystudio107/craft-vite#56]
### Describe the bug
I'm unable to reference static assets that are imported via JS and appear in the manifest, e.g. `{{ craft.vite.asset("src/sprite.svg") }}`.

### Expected behaviour
The asset function should return the hashed path to assets in production. It appears the issue exists in `extractAssetFiles` in [ManifestHelper.php]( (https://github.com/nystudio107/craft-plugin-vite/blob/develop/src/helpers/ManifestHelper.php#L324)), as it's looking for an `assets` key that doesn't exist in modern manifests.

### Example Manifest
```json
{
  "src/scripts/site-legacy.js": {
    "file": "assets/app-legacy-383a340e.js",
    "src": "src/scripts/site-legacy.js",
    "isEntry": true
  },
  "vite/legacy-polyfills-legacy": {
    "file": "assets/polyfills-legacy-e1be769e.js",
    "src": "vite/legacy-polyfills-legacy",
    "isEntry": true
  },
  "src/sprite.svg": {
    "file": "assets/sprite-dea648df.svg",
    "src": "src/sprite.svg"
  },
  "src/scripts/site.js": {
    "file": "assets/app-deed8d93.js",
    "src": "src/scripts/site.js",
    "isEntry": true
  }
}
```

### Versions
- Plugin version: 4.0.4
- Craft version: 4.3.6.1
- Vite version: 4.0.4

**Comment by khalwat** [comment]
Looks like their docs may be out of date in terms of the manifest format: https://vitejs.dev/guide/backend-integration.html

**Comment by khalwat** [comment]
Relevant changes:

https://github.com/vitejs/vite/pull/6649

https://github.com/vitejs/vite/pull/8768

**Comment by khalwat** [comment]
Released a fix for this:

Craft 3: Version 1.0.30 -> https://github.com/nystudio107/craft-vite/releases/tag/1.0.30

Craft 4: Version 4.0.5 -> https://github.com/nystudio107/craft-vite/releases/tag/4.0.5
