### ISSUE TITLE
Default config.php relies on non-standard environment variable

### ISSUE THREAD

**Issue by ItagMichael** [nystudio107/craft-vite#6]
In the sample config.php, `useDevServer` is set via a `DEV_MODE` env variable, however pretty sure CraftCMS doesn't ship with this in .env nor does it set it by itself.

Consider replacing with `App::env('ENVIRONMENT') === 'dev'` which is how CraftCMS sets its devMode out of the box.

**Comment by khalwat** [comment]
Probably the best practice would be if people used a separate `.env` variable for it like `VITE_USE_DEV_SERVER`. But then that would be "non-standard" as well.

All of my boilerplate setups include a `DEV_MODE` environment variable, and I don't think it's a particularly uncommon practice.

Still, to avoid support, probably `App::env('ENVIRONMENT') === 'dev'` is a reasonable compromise.

**Comment by khalwat** [comment]
Addressed in https://github.com/nystudio107/craft-vite/commit/13981b09331ca6f38b5db531de864ec4726a90bd

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-vite": "dev-develop as 1.0.6”,
```
Then do a `composer clear-cache && composer update`
