### ISSUE TITLE
Twigpack::$plugin->manifest->getFileFromManifest() equivalent

### ISSUE THREAD

**Issue by Saboteur777** [nystudio107/craft-vite#62]
### Question
I have an endpoint with a static url (e.g.: `domain.com/api/v1/script.js`), which serves the contents of one file from the manifest (e.g.: `script.2040123.js`).

With Twigpack I used the following code for this: 

```
    public function actionJs()
    {
        Craft::$app->response->format = Response::FORMAT_RAW;
        Craft::$app->response->headers->set('Content-Type', 'application/javascript');

        return Twigpack::$plugin->manifest->getFileFromManifest('shoprenter.js.map', 'modern');
    }
```

What is the equivalent of this with Vite?

**Comment by khalwat** [comment]
You're trying to return the `.map` file?

**Comment by khalwat** [comment]
Anyway, maybe something like:

https://github.com/nystudio107/craft-plugin-vite/blob/develop/src/services/ViteService.php#L288

```php
Vite::$plugin->vite->entry($path);
```

**Comment by Saboteur777** [comment]
Yes, and also the js file. 

A little explanation: I have a SaaS site, where one of the generated files can be embedded/invoked by a third party website. So Vite bundles the JS & sourcemap files, but the path of it is constantly changing, so I serve the content of these files on an endpoint. 

Thanks, I will check it out right away.

**Comment by Saboteur777** [comment]
@khalwat I got this error: 

```
Getting unknown property: nystudio107\vite\Vite::viteService
```

This is working: 
```
Vite::$plugin->vite->entry($path);
```
