### ISSUE TITLE
Multi-domain setup

### ISSUE THREAD

**Issue by sander-lameco** [nystudio107/craft-vite#65]
Not sure if this should be asked here or in the Craft CMS repo, so please excuse me if I'm wrong.

### Question
We have a multi-(sub)domain setup within a single Craft CMS and single `.env` file: `insights.xximo.com` and `www.xximo.com`.
Sometimes when visiting `insights.xximo.com` we get errors like:
```
Access to script at 'https://www.xximo.com/dist/assets/app.089fed21.js' from origin 'https://insights.xximo.com' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://www.xximo.com' that is not equal to the supplied origin.
```

Now this might be something we could fix on the server side for the `'Access-Control-Allow-Origin' header` but we are wondering if it is also possible to change the `'serverPublic'` in `config/vite.php` in a way to check on the currentSite handle or something? We can only find multi-environment configurations but not multi-site configurations.

**Comment by sander-lameco** [comment]
Seems to be working if I replace `'serverPublic' => App::env('PRIMARY_SITE_URL') . 'dist/',` with `'serverPublic' => 'dist/',` but is this a viable solution?

**Comment by khalwat** [comment]
Yep seems reasonable!
