### ISSUE TITLE
.getCssInlineTags() function produces encoded output

### ISSUE THREAD

**Issue by thupsi** [nystudio107/craft-vite#67]
### Describe the bug
The newly introduced `.getCssInlineTags()` function is supposed to return a raw/unencoded string, yet the style tags that wrap the file contents are somehow getting encoded.

I reported this behaviour in discord and it is indeed strange, as Andrew indicated, because the function is wrapped in `Template::raw()` -> <https://github.com/nystudio107/craft-vite/blob/develop/src/variables/ViteVariable.php#L57>

Just wanted to post this here, in case somebody else runs into the same problem. 

I should further point out that the simple workaround is to use the `|raw` twig filter like so: 
```
 {{ craft.vite.getCssInlineTags("@webroot/path/to/css/file.css")|raw }}
```

### To reproduce
Steps to reproduce the behaviour:
1. Have a `test.css` file, let's say:
```
body {
    background-color: red;
} 
```
2. Have a `test.twig` template, let's say:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Document</title>
		{{ craft.vite.getCssInlineTags("@webroot/test.css") }}
	</head>
	<body></body>
</html>

```
3. The result is:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Document</title>
		&lt;style&gt;body {
    background-color: red;
} &lt;/style&gt;
	</head>
	<body></body>
</html>
```

### Expected behaviour
The result should be:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Document</title>
		<style>body {
    background-color: red;
} </style>
	</head>
	<body></body>
</html>
```

### Versions
- Plugin version: 4.0.6
- Craft version: 4.4.13

**Comment by khalwat** [comment]
I'm not sure what to say, it looks right in the code, and is using `Template::raw()` like everything else is:

https://github.com/nystudio107/craft-vite/blob/develop/src/variables/ViteVariable.php#L57
