### ISSUE TITLE
Loading svg icons in css async (production)

### ISSUE THREAD

**Issue by Toni-hr98** [nystudio107/craft-vite#69]
### Describe the bug
Load the css async. In the css add a background-image. 

Example: "background: url("@/img/site/icon-right.svg") no-repeat;"

Now build vite for production and open the developer tools -> network tab in the browser. You will see a lot of icon network requests. If not... hover over the icon and you will see the requests popping up.

### Expected behaviour
Just load the icon once and stop infinity requests

### Screenshots
![Schermafbeelding 2023-07-06 om 14 40 52](https://github.com/nystudio107/craft-vite/assets/56109782/b4318fea-21a9-4910-9b5e-386eab3c89a4)

![Schermafbeelding 2023-07-06 om 14 39 09](https://github.com/nystudio107/craft-vite/assets/56109782/ce6da1ff-6a17-4deb-b5f9-ccbb09f4232e)

### Versions
- Plugin version: 4.0.5
- Craft version: 4.4.5

**Comment by khalwat** [comment]
This does not relate to the Craft Vite plugin -- I'd suggest posting the question on the Vite repository or in the Vite discord.
