### ISSUE TITLE
Can't make HMR detect TWIG changes

### ISSUE THREAD

**Issue by goraxan** [nystudio107/craft-vite#7]
### Question
I'm trying to configure Vite with HMR for twig pages, as said in the documentation https://nystudio107.com/docs/vite/#live-reload-of-twig-config but it doesn't seem to work.

My project is just a vanila CraftCMS installation with the craft-vite plugin installed and some twig templates under the `templates` folder
I've created a src/js/app.ts inside the project, with the following content:
```
import "/templates/static/modules/_css_global/style.less"

console.log("start");
```
I've created a vite.config.js file in the root:
```
import ViteRestart from 'vite-plugin-restart';

// https://vitejs.dev/config/
export default ({ command }) => ({
  base: command === 'serve' ? '' : '/dist/',
  build: {
    manifest: true,
    outDir: './web/dist/',
    rollupOptions: {
      input: {
        app: './src/js/app.ts',
      }
    },
  },
  plugins: [
    ViteRestart({
      reload: [
          './templates/**/*',
      ],
    }),
  ],
});
```
I've created a config/vite.php file with the following contents:
```
return [

   /**
    * @var bool Should the dev server be used?
    */
    'useDevServer' => App::env('ENVIRONMENT') === 'dev',

    /**
     * @var string File system path (or URL) to the Vite-built manifest.json
     */
    'manifestPath' => '@webroot/dist/manifest.json',

    /**
     * @var string The public URL to the dev server (what appears in `<script src="">` tags
     */
    'devServerPublic' => 'http://localhost:3000/',

    /**
     * @var string The public URL to use when not using the dev server
     */
    'serverPublic' => App::env('PRIMARY_SITE_URL') . '/dist/',

    /**
     * @var string The JavaScript entry from the manifest.json to inject on Twig error pages
     *              This can be a string or an array of strings
     */
    'errorEntry' => '',

    /**
     * @var string String to be appended to the cache key
     */
    'cacheKeySuffix' => '',

    /**
     * @var string The internal URL to the dev server, when accessed from the environment in which PHP is executing
     *              This can be the same as `$devServerPublic`, but may be different in containerized or VM setups.
     *              ONLY used if $checkDevServer = true
     */
    'devServerInternal' => '',

    /**
     * @var bool Should we check for the presence of the dev server by pinging $devServerInternal to make sure it's running?
     */
    'checkDevServer' => false,
];

```

I've created a twig file with the following line head section
`{{ craft.vite.script("/src/js/app.ts") }}`

Vite is detecting LESS (CSS) changes and reloading the page, but not TWIG changes. It looks like it starts fine according to the console logs
![image](https://user-images.githubusercontent.com/8337784/118960243-60b04e00-b963-11eb-8dcf-b76bc75e3ccb.png)

Any clues about what is happening here? I'm on Windows. PHP runs with a XAMPP server (PHP 7.4), whereas vite.js runs by typing `npm run dev`
![image](https://user-images.githubusercontent.com/8337784/118961255-6b1f1780-b964-11eb-8395-9ddd367ede6c.png)

Thanks

### Additional context
Also, I've configured a new project from https://github.com/nystudio107/craft/tree/craft-vite and it does detect twig changes, but as soon as I remove vue (which I don't need in my project) it stops working. It looks like HMR for twig is done through a Vue.js component, is that correct?

**Comment by khalwat** [comment]
So probably you need to do something Windows-specific here, but I'm sorry, I just don't know what that would be.

I do know that it uses `chokidar` to detect filesystem changes:

https://github.com/paulmillr/chokidar

Here's the key bit:

```js
    ViteRestart({
      reload: [
          './templates/**/*',
      ],
```

is `./templates/` the directory where your templates are? If not, you'll need to change it.

Maybe there's something Windows-specific that needs to be done here in specifying the directory?

This doesn't really have anything to do with the Vite plugin tho, it's related to Vite itself (or possibly `chokidar` or the `ViteRestart` plugin), so I'd check those resources for insights.

Sorry I don't have a better answer for your particular local dev setup.

**Comment by goraxan** [comment]
Well, I'll stick to webpack then, which is working just fine. Thanks.

**Comment by khalwat** [comment]
webpack uses the same package (chokidar) to detect file system changes, FWIW.

**Comment by khalwat** [comment]
Someone using Windows mentioned that you might need to turn polling on as per the instructions for Vagrant here: 

https://nystudio107.com/docs/vite/#local-development-environment-setup

```js
  server: {
    host: '0.0.0.0',
    watch: {
        usePolling: true,
    },
  },
```
