### ISSUE TITLE
Failed to connect to localhost port 3000

### ISSUE THREAD

**Issue by shifuma** [nystudio107/craft-vite#74]
### Question

I'm getting this error locally: `cURL error 7: Failed to connect to localhost port 3000: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost:3000/__vite_ping`

It has no effect; I'm able to build assets without issue, but I'd like to fix it. Unfortunately, I am absolutely clueless when it comes to this sort of thing. I'm just using a standard DDEV setup, nothing special configured.

I'm guessing `'devServerInternal' => 'http://localhost:3000/',` is incorrect, but how can I find out what it should be?

Thanks in advance!

**Comment by shifuma** [comment]
Oh...maybe it's just as simple as `'devServerInternal' => 'http://mysite.ddev.site:3000/',` ... ?

**Comment by khalwat** [comment]
Did you check the docs for DDEV configuration? 

https://nystudio107.com/docs/vite/#using-ddev

if so, probably you have not opened up port 3000 in ddev to be exposed to your local environment.

**Comment by shifuma** [comment]
Thanks for the reply. Yeah, everything matches those 'Using DDEV' docs.

**Comment by jesuismaxime** [comment]
Followed the documentation, double check with ddev's  and I got that very same error. Any lead?

**Comment by jesuismaxime** [comment]
Just got that issue on a production website (that causes some trouble because of huuuuge logs files), simply turn `useDevServer` at `false` on non-local environments.
