### ISSUE TITLE
manifest.json path vite 5

### ISSUE THREAD

**Issue by mhuch** [nystudio107/craft-vite#77]
Hello.

When I integrated the plugin into my code, I noticed that if the DEV_MODE is set to false, the script and link tags are not created.
The problem was that I copied the manifest path from your documentation `@webroot/dist/manifest.json`.
But since I use vite version 5 the path of the manifest.json is this one `@webroot/dist/.vite/manifest.json`.

Max.

**Comment by khalwat** [comment]
Yes, you can either change the path to include `.vite/` if you're using Vite 5, or in your Vite config, you can change it from:

```js
manifest: true,
```

to:

```js
manifest: 'manifest.json',
```
