### ISSUE TITLE
Having trouble with asset loading after build

### ISSUE THREAD

**Issue by sg-modlab** [nystudio107/craft-vite#78]
### Question
So when I run my serve script all is working well, but when I run build and look at site locally (not serving) my js file and css file are not being added.

### Additional context

Serve seeing this:

`<script type="module" src="https://modl-craft-starter.ddev.site:3000/src/js/app.js"></script>`

After build and direct view locally seeing this:

`<script type="module">
    !function() {
        const e = document.createElement("link").relList;
        if (!(e && e.supports && e.supports("modulepreload"))) {
            for (const e of document.querySelectorAll('link[rel="modulepreload"]'))
                r(e);
            new MutationObserver((e => {
                for (const o of e)
                    if ("childList" === o.type)
                        for (const e of o.addedNodes)
                            if ("LINK" === e.tagName && "modulepreload" === e.rel)
                                r(e);
                            else if (e.querySelectorAll)
                                for (const o of e.querySelectorAll("link[rel=modulepreload]"))
                                    r(o)
            })).observe(document, {
                childList: !0,
                subtree: !0
            })
        }
        function r(e) {
            if (e.ep)
                return;
            e.ep = !0;
            const r = function(e) {
                const r = {};
                return e.integrity && (r.integrity = e.integrity), e.referrerpolicy && (r.referrerPolicy = e.referrerpolicy), "use-credentials" === e.crossorigin ? r.credentials = "include" : "anonymous" === e.crossorigin ? r.credentials = "omit" : r.credentials = "same-origin", r
            }(e);
            fetch(e.href, r)
        }
    }();
    </script>`

Hoping for a lead to help me troubleshoot where my issue might be.

**Comment by sg-modlab** [comment]
I think I figured it out. In the `vite.php` config. I had to adjust the following line to include the `.vite/` segment. Wondering if that changed from v4 -> v5.

`'manifestPath' => Craft::getAlias('@webroot') . '/dist/.vite/manifest.json',`

**Comment by khalwat** [comment]
Yes, that's a change they made in Vite 5 -- but I'd suggest instead just modifying your Vite config like this:

```
    manifest: 'manifest.json',
```

(it's now a `boolean` or `string`, and if it's a string, it's a path to your manifest file you want generated)

This will keep the manifest in the default location it was in for Vite 4.x and previous.
