### ISSUE TITLE
Preview version for craft v5 already installable via composer?

### ISSUE THREAD

**Issue by mandrasch** [nystudio107/craft-vite#79]
### Question

Hi, I'm trying to update my demo repository 

https://github.com/mandrasch/ddev-craftcms-vite/

to v5 alpha: 

https://github.com/mandrasch/ddev-craftcms-vite/tree/craftcms-v5-alpha

I tried installing the v5 branch version of this plugin via

```
ddev composer require nystudio107/craft-vite:dev-develop-v5 && ddev exec php craft plugin/install vite
```

But this results in

```
./composer.json has been updated
Running composer update nystudio107/craft-vite
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires nystudio107/craft-vite dev-develop-v5 -> satisfiable by nystudio107/craft-vite[dev-develop-v5].
    - nystudio107/craft-vite dev-develop-v5 requires nystudio107/craft-plugin-vite ^5.0.0-beta.1 -> found nystudio107/craft-plugin-vite[dev-develop-v4, dev-develop-v5, dev-develop, 1.0.0, ..., v1.x-dev, 4.0.0-beta.1, ..., v4.x-dev] but it does not match the constraint.
    
Installation failed, reverting ./composer.json and ./composer.lock to their original content.
Composer [require nystudio107/craft-vite:dev-develop-v5] failed, composer command failed: exit status 2. stderr=
```

(`^5.0.0-beta.1` is not yet listed here https://packagist.org/packages/nystudio107/craft-plugin-vite)

If it is way too soon for trying it out, please just close this issue 😉  I was just curious.

Thanks for providing this awesome plugin! 🙏 

Best regards,
Matthias

**Comment by khalwat** [comment]
Yeah, it's not ready for prime time yet... it'll all work when I publish the above packages. My plan is to wait for the beta version of Craft 5 before doing so.

The changes are really minor, just changing the semver in the plugin really... but there's some other "chrome" around it all (docs, etc.) that I need to sort out.

**Comment by mandrasch** [comment]
Hi @khalwat, thanks very much for information! 👍 👋

**Comment by khalwat** [comment]
Have fun... https://github.com/nystudio107/craft-vite/releases/tag/5.0.0-beta.1

**Comment by mandrasch** [comment]
> Have fun... https://github.com/nystudio107/craft-vite/releases/tag/5.0.0-beta.1

Awesome, thanks very much! 🎉 (Got it working https://github.com/mandrasch/ddev-craftcms-vite/tree/craftcms-v5-alpha)
