### ISSUE TITLE
Incorrect return from getCssHash()

### ISSUE THREAD

**Issue by raray** [nystudio107/craft-vite#80]
### Describe the bug
As of 4.0.7, `getCssHash()` is incorrectly removing a section of the hash if it includes a dash. For instance, this hash is being reported as `rmXHq`:
```
"asset-src/build/main-preload.js": {
    "css": [
      "main-preload.G7-rmXHq.css"
    ],
...
```
This is appears to be related to changes made for https://github.com/nystudio107/craft-plugin-vite/issues/21. Reverting to `4.0.6` resolves the issue.

### Versions
- Plugin version: 4.0.7
- Craft version:4.7.0

**Comment by khalwat** [comment]
What version of Vite are you using?

**Comment by khalwat** [comment]
Addressed in the commits above.

Craft CMS 3:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-vite": "dev-develop as 1.0.34”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 4:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-vite": "dev-develop-v4 as 4.0.9”,
```
Then do a `composer clear-cache && composer update`

…..

Craft CMS 5:

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-vite": "dev-develop-v5 as 5.0.0-beta.3”,
```
Then do a `composer clear-cache && composer update`
