### ISSUE TITLE
CriticalCSS + entry types

### ISSUE THREAD

**Issue by jessedobbelaere** [nystudio107/craft-vite#81]
### Question
I'm using the `{{ craft.vite.includeCriticalCssTags() }}` snippet. Recently I moved all my Singles to entries by creating a Pages section with one template `_pages/entry.twig`. Then created multiple entry types for specific layouts (default, home, contact).

The `_pages/entry.twig` will dynamically load one of the different entry types (`_pages/default.twig`, `_pages/home.twig`, ...) using the setup from [darylknight](https://github.com/darylknight/boilerplate/blob/main/templates/_pages/_entry.twig)

```twig
{# Load the template for this Entry Type #}
{% include '_pages/' ~ entry.type %}
```

However, this setup breaks the `includeCriticalCssTags`, because all the routes I generate CriticalCSS for, try to include the criticalcss of `_pages/entry`:

```php
$template = Craft::$app->getView()->resolveTemplate($name ?? Vite::$templateName ?? '');
// _pages/entry.twig
```

In `criticalPages`, I tried to add multiple uri's with the same `_pages/entry` template, however, rollup-plugin-critical generates the css per page and does not merge any of them, it overwrites. The critical package doesn't support multiple src. In this example, only the /contact css remains. 

```javascript
criticalPages: [
    { uri: `/`, template: '_pages/entry' },
    { uri: `/contact`, template: '_pages/entry' },
],
```

👉 I suppose my only solution would be to stop using `craft.vite.includeCriticalCssTags`, write the actual template instead of `_pages/entry` in the `criticalPages`, 

```javascript
criticalPages: [
    { uri: `/`, template: '_pages/home' },
    { uri: `/contact`, template: '_pages/contact' },
],
```

then write a twig macro to include a hardcoded critical css file (if exists) with `craft.vite.inline` in each of my entry types? Or are there better suggestions?

**Comment by jessedobbelaere** [comment]
Settled on this macro, but let me know if there's room for improvement:

```twig
{# _macros/critical.twig #}
{% macro includeCriticalCssTags(template) %}
    {% set criticalCss = '@webroot/dist/criticalcss/' ~ template ~ '_critical.min.css' %}
    {{ craft.vite.getCssInlineTags(criticalCss)|raw }}
{% endmacro %}
```

And usage in one of my entry templates like:

```twig
{% import '_macros/critical' as critical %}

{% block css %}
    {{ critical.includeCriticalCssTags(_self) }}
{% endblock %}
```

**Comment by khalwat** [comment]
If it works for you, it's great! :)
