### ISSUE TITLE
Uninstallable with the Craft 5 Beta

### ISSUE THREAD

**Issue by JayBox325** [nystudio107/craft-vite#84]
### Describe the bug
Tried to install this plugin on a brand new CraftCMS 5 project, and it throws an installable set of packages error. If this plugin isn't ready for Craft 5 yet, the Compatibility label in the Plugin Store should be amended.

### To reproduce
Steps to reproduce the behaviour:
1. Setup a brand new DDEV + Craft 5 Beta project.
2. Install this plugin from the Command Line or the Plugin Store
3. Both times it errors.

### Error message
```
ddev composer require nystudio107/craft-vite
Using version ^4.0 for nystudio107/craft-vite
./composer.json has been updated
Running composer update nystudio107/craft-vite
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - nystudio107/craft-vite[4.0.0-beta.1, ..., 4.0.0-beta.3] require craftcms/cms ^4.0.0-alpha -> found craftcms/cms[4.0.0-alpha.1, ..., 4.8.x-dev] but it conflicts with your root composer.json require (^5.0.0-alpha.1).
    - nystudio107/craft-vite 4.0.0-beta.4 requires craftcms/cms ^4.0.0-beta.1 -> found craftcms/cms[4.0.0-beta.1, ..., 4.8.x-dev] but it conflicts with your root composer.json require (^5.0.0-alpha.1).
    - nystudio107/craft-vite[4.0.0, ..., v4.x-dev] require craftcms/cms ^4.0.0 -> found craftcms/cms[4.0.0-alpha.1, ..., 4.8.x-dev] but it conflicts with your root composer.json require (^5.0.0-alpha.1).
    - Root composer.json requires nystudio107/craft-vite ^4.0 -> satisfiable by nystudio107/craft-vite[4.0.0-beta.1, ..., v4.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require nystudio107/craft-vite:*" to figure out if any version is installable, or "composer require nystudio107/craft-vite:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
composer [require nystudio107/craft-vite] failed, composer command failed: exit status 2. stderr=
```

### Versions
- Plugin version: 4.0
- Craft version: Craft 5

**Comment by khalwat** [comment]
> Tried to install this plugin on a brand new CraftCMS 5 project, and it throws an installable set of packages error. If this plugin isn't ready for Craft 5 yet, the Compatibility label in the Plugin Store should be amended.

The plugin works fine with Craft 5 beta -- but you're attempting to install the Craft 4 version of the plugin.

The semver version you want is `^5.0.0-beta.1` -> https://github.com/nystudio107/craft-vite/releases/tag/5.0.0-beta.2

How did you attempt to install the plugin such that it's requiring the Craft 4 version?

**Comment by JayBox325** [comment]
I just installed the latest version of the plugin from the plugin store. Didn't realise there was a Craft 5 beta version of the plugin. My misunderstanding. Thank you.
