### ISSUE TITLE
vite.php - The artifactUrl Twig function has been deprecated. Use cloud.artifactUrl instead.

### ISSUE THREAD

**Issue by bryandugan** [nystudio107/craft-vite#86]
I looked at the example code [provided in the docs](https://nystudio107.com/docs/vite/#craft-cloud) to configure my vite.php file with ddev/craft cloud and am getting some deprecation warnings.

Here is a look at the deprecation error that I'm getting
![artifacturl-deprecation-errror](https://github.com/nystudio107/craft-vite/assets/4441531/d9462393-fd09-4e12-bd9e-773e29f07677)

I've tried changing `artifactUrl` with `cloud.artifactUrl`, but am getting errors and don't know how to update the code.

vite.php
```
<?php

use craft\helpers\App;
use craft\cloud\Helper as CloudHelper;

return [
    'checkDevServer' => true,
    'devServerInternal' => 'http://localhost:3000',
    'devServerPublic' => Craft::getAlias('@web') . ':3000',
    'errorEntry' => 'src/js/app.js',
    'manifestPath' => CloudHelper::isCraftCloud() ? CloudHelper::artifactUrl('dist/manifest.json') : '@webroot/dist/manifest.json',
    'serverPublic' => CloudHelper::artifactUrl('dist/'),
    'useDevServer' => (bool)App::env('VITE_USE_DEV_SERVER'),
];

```

**Comment by khalwat** [comment]
This looks like something P&T needs to update on their end, since we're using the provided `CloudHelper` class, which is under their control... and presumably should not be throwing deprecation notices.

**Comment by timkelty** [comment]
@bryandugan what version of `cloudcms/cloud` are you on? As of [1.49.2](https://github.com/craftcms/cloud-extension-yii2/releases/tag/1.49.2) those deprecation notices should no longer be logged.

**Comment by bryandugan** [comment]
@timkelty I am running `"craftcms/cloud": "^2.4.2",`  with the current version being 2.4.2. The last instance of the deprecation warning showing was about a minute ago.

**Comment by timkelty** [comment]
@bryandugan I can't reproduce this. Can you try clearing your template cache?

A check of [the code](https://github.com/craftcms/cloud-extension-yii2/blob/2.4.2/src/twig/TwigExtension.php#L39-L46) confirms that it should only be logged when `artifactUrl` is called directly.

**Comment by bryandugan** [comment]
This was definitely a me issue. I thought I had to change the configuration in my `vite.php` file, but I needed to change my layout template files to say `cloud.artifactUrl` instead of `artifactUrl` while serving up my favicon files and other static assets.
