### ISSUE TITLE
Getting clear on how it works in real world as local url is appearing in live staging site

### ISSUE THREAD

**Issue by alanski66** [nystudio107/craft-vite#87]
Have this working locally ok DDev, Craft 4 latest plugin
### Question
The tag:  {{ craft.vite.script("assets/js/app.js", false) }} - is this intended for dev, staging, and production?

When pushed to staging server (ENV=dev) what is getting output is:
<script type="module" src="http://localhost:5173/assets/js/app.js"></script>
Is this because of DEV env or something else?

Also is vite config only used in dev? Does it need changing for each ENV?

Any light welcome:)

**Comment by khalwat** [comment]
Yes, you use the same tag in all environments.

What it should do in each environment is determined in the `config/vite.php` file:

https://nystudio107.com/docs/vite/#the-config-php-file

**Comment by alanski66** [comment]
Just to add - I wasnt ready for this to close :(

So my issue appears to be devServerPublic settings - great.
But what determines 'when not using the dev server' ?
Is this by env variable in .env?

   'devServerPublic' => 'http://localhost:5173/',

    /**
     * @var string The public URL to use when not using the dev server
     */
    'serverPublic' => App::env('PRIMARY_SITE_URL') . '/dist/',

**Comment by khalwat** [comment]
The `useDevServer` setting determines whether the dev server will be used or not: https://nystudio107.com/docs/vite/#configuring-vite
