### ISSUE TITLE
Support ddev share

### ISSUE THREAD

**Issue by Metis77** [nystudio107/craft-vite#88]
is there any config, that makes  `ddev share` working?
Could not fine any solution in the Docu or the issues.

**Comment by bymayo** [comment]
Would like this also, the issue seems to be that the share works but the styles don't load due to it loading the localhost URL.

**Comment by Metis77** [comment]
> Would like this also, the issue seems to be that the share works but the styles don't load due to it loading the localhost URL.

yes.
actually it works, when updating the primary url. but than local wont work.
I thought of a conditional primary url, while having the same .env.

**Comment by khalwat** [comment]
If anyone comes up with a solution, PR the docs -- I'd love to include it.

Meanwhile, I'll close this issue since I don't think it really has much to do with the Vite plugin itself.

**Comment by iamtompickering** [comment]
@Metis77 curious to know if you ever found a solution to this? Having the same issue myself.

**Comment by Metis77** [comment]
> @Metis77 curious to know if you ever found a solution to this? Having the same issue myself.

Sorrily not. I think thats something that needs to be solved in craft or ddev, by recognising source of request.
