### ISSUE TITLE
Unexpected onload attribute

### ISSUE THREAD

**Issue by smth** [nystudio107/craft-vite#89]
### Question
In the docs it says the production output will be something like `<script type="module" src="https://example.com/dist/assets/app.56c9ea9d.js" crossorigin></script>`. What I'm seeing is `<script type="module" src="/dist/assets/app-Bh0WP9T6.js" crossorigin="" onload="e=new CustomEvent('vite-script-loaded', {detail:{path: 'src/js/app.js'}});document.dispatchEvent(e);"></script>`, preceded by an inline script. What might I be missing to end up with this?

### Additional context
I'm using ddev, just switching the env variable to "production" to get the above output.

**Comment by khalwat** [comment]
This is all correct and expected, it's so you can listen for the scripts being loaded. If you don't want it, set `includeScriptOnloadHandler` to `false` in your `config/vite.php` file as described here:

https://nystudio107.com/docs/vite/#the-config-php-file
