### ISSUE TITLE
CSS_TAG_ATTRS on the dev server

### ISSUE THREAD

**Issue by FrDH** [nystudio107/craft-vite#93]
### Question
I'm having trouble getting my print.css to work on the dev server. It appears the CSS_TAG_ATTRS (as described [here](https://nystudio107.com/docs/vite/#other-options)) don't work with HRM, i.e. when the dev server is running:
```` 
{# in twig #}
{{ craft.vite.register("js/print.js", false, {
   media: "print"
})
````
````
// in print.js
import '../scss/print.scss';
````

The problem in this case is that the `media: "print"` attribute isn't applied and everything looks ugly :)

I found a workaround by importing the css with `?inline` and adding it to a `<style>` tag in print.js:
````
{# in twig #}
{{ craft.vite.register("js/print.js", false)
````
````
// in print.js
import styles from '../scss/print.scss?inline';

window.addEventListener('load', () => {
    const style = document.createElement('style');
    style.media = "print";
    style.innerText = styles;
    document.head.appendChild(style);
});
````

Although this works, it's not ideal because this creates really large chunks of inline styles for all stylesheets that need attributes. And it's only needed for local development...

Am I missing something?

**Comment by khalwat** [comment]
Correct, since the Vite dev server is providing the scripts/css, etc. during local development, the Craft Vite plugin is not involved, and cannot set things like the `CSS_TAG_ATTRS`
